signaux-faibles/opensignauxfaibles

README.md
...pour parer aux erreurs `undefined: jsFunctions` lors de la compilation.
=> fix(docs): Mise à jour des instructions d'installation

.github/workflows/go.yml, .gitignore, README.md, dbmongo/js/test/compact/test_finalize.js, dbmongo/js/test/compact/test_reduce.js, dbmongo/js/test/testing.js, dbmongo/js_test.go, dbmongo/lib/engine/js/loadJS.go, dbmongo/lib/engine/main_test.go
Cette PR permet de cloner, générer, compiler et tester (au moins en partie) la codebase sur GitHub actions, sur chaque commit fusionné dans `master` et sur chaque PR, pour nous permettre d'identifier toute regression qu'ils pourraient causer.
Autres correctifs apportés:
- exclure tous les tests du bundle `jsFunctions.go` => sa taille passe de 15k à 2k lignes ! ✨
- dans README: appeler `go generate` depuis `lib/engine`
- faire en sorte que `main_test.go` ne cause pas d'erreur d'importation, lors du `go get -t`
- re-formattage de certains fichiers JS => je recommande d'ignorer les diff de whitespace, lors de la relecture
=> feat(ci): Mise en place de l'Intégration Continue + correctifs nécessaires

dbmongo/js/test/test_map_reduce_algo2.sh, dbmongo/js_test.go
* Le flag "--update" peut être directement passé à la commande `go test`
* Documentation du flag "--update" dans le fichier test_map_reduce_algo2.sh
=> tests: --update pour le golden file accessible dans go test

.github/workflows/go.yml, .gitignore, dbmongo/lib/engine/jsFunctions.go
* Ajout jsFunctions.go au dépôt
* Intégration continue vérifie que le fichier correspond à la dernière version en le comparant au résultat d'un nouveau `go generate`
Cela permet de s'assurer que les tests ne sont pas ajoutés à jsFunctions.go par accident.
=> tests(ci): ajout jsFunctions.go au dépôt et vérification que le fichier est à jour

dbmongo/js/reduce.algo2/map_test.js, dbmongo/js/test/test_map_reduce_algo2.sh
Suite de #28.
Ce n'est qu'une proposition. Ravi d'en discuter ensemble !
=> tests: Restructuration des tests .js – partie 3

dbmongo/lib/engine/reduce.go
Pour voir si j'ai bien compris.
=> docs: Commentaires sur pipeline d'intégration map-reduce

README.md
Sera complété par une procédure plus détaillée (en cours d'écriture) dans le dépot `documentation`.
=> docs: Configuration et usage

dbmongo/js/reduce.algo2/finalize_test.js, dbmongo/js/reduce.algo2/map_test.js, dbmongo/js/test/test_finalize_algo2.sh, dbmongo/js/test/test_map_algo2.sh
Test par golden file, similairement à celui du `map`. Test non exécuté en CI, pour des raisons de confidentialité des données.
Effectué en pair avec @JazzyPierrot.
=> tests(JS): Test du finalize de la phase de calculs

.github/workflows/go.yml, .gitignore, dbmongo/js/.editorconfig, dbmongo/js/.eslintrc.js, dbmongo/js/.prettierrc.js, dbmongo/js/common/raison_sociale.js, dbmongo/js/common/raison_sociale.ts, dbmongo/js/package-lock.json, dbmongo/js/package.json, dbmongo/js/reduce.algo2/fraisFinancier.js, dbmongo/js/reduce.algo2/fraisFinancier.ts, dbmongo/js/reduce.algo2/fraisFinancier_tests.ts, dbmongo/js/reduce.algo2/map_tests.ts, dbmongo/js/tsconfig.json, dbmongo/lib/engine/jsFunctions.go
La CI va désormais vérifier que notre code source TypeScript respecte bien:
- nos conventions de codage exprimées dans `.eslintrc.js` (tolérer l'usage d'underscores dans les noms de fonctions et variables)
- et nos conventions de formatage exprimées dans `.editorconfig` (indentation à 2 espaces) et `.prettierrc.js` (interdiction d'usage de points-virgules après chaque instruction)
Exemple: https://github.com/signaux-faibles/opensignauxfaibles/pull/46/checks?check_run_id=670979685#step:9:86
Cette PR applique également les modifications recommandées par le linter.
Exécution du linter en local:
```sh
$ cd dbmongo/js
$ npm install
$ npm run lint
$ npm run lint:fix # va aussi reformater les fichiers .ts
```
Pour intégrer les retours du linter et re-formater automatiquement les fichiers à …
=> chores(js): Ajout d'une configuration et script de formatage et linter

dbmongo/js/reduce.algo2/delais.ts, dbmongo/js/reduce.algo2/delais_tests.ts, dbmongo/js/reduce.algo2/map.js, dbmongo/lib/engine/jsFunctions.go
* Ajout d'un test qui était en todo. 
* fix: les propriétés de `DebitComputedValues` deviennent optionnelles
* Refacto des types 
* La fonction `delais` est pure
=> fix(TS): Sécurisation de la fonction `delais` + ajout d'un test

dbmongo/js/compact/currentState.ts, dbmongo/lib/engine/jsFunctions.go
cf https://github.com/signaux-faibles/opensignauxfaibles/pull/67#discussion_r441643552
=> fix(compact): Usage d'une boucle for pour se passer d'objet par défaut

dbmongo/js/compact/applyPatchesToBatch.ts, dbmongo/js/compact/applyPatchesToMemory.ts, dbmongo/js/compact/compactBatch.ts, dbmongo/js/compact/fixRedundantPatches.ts, dbmongo/js/compact/listHashesToAddAndDelete.ts, dbmongo/js/compact/reduce.ts, dbmongo/js/compact/reduce_test.js, dbmongo/lib/engine/jsFunctions.go
Effectué en pair avec @JazzyPierrot
=> refactor(compact): Extraction de fonctions pour chaque étape

test-api-2.sh, test-api.sh
Inspiré du script de tests implémenté dans PR #85.
- Moins de logs pour plus de lisibilité des résultats (et erreurs éventuelles) d'exécution des tests d'API / bout en bout
- Support du flag `--update` pour mettre à jour les fichier golden master
- Suppression des données non nécessaires
=> fix(tests): Mise à jour de golden master + nettoyage code & logs

dbmongo/data.go, dbmongo/handlers.go, dbmongo/js/reduce.algo2/effectifs.ts, dbmongo/lib/engine/data.go, dbmongo/lib/engine/jsFunctions.go
Effectué en pair avec Pierre.
Changements:
- application de 2 `TODO`s
- cf commits et diff.
=> fix: Simplification de effectifs.ts (reduce.algo2) + améliorations Go

dbmongo/js/RawDataTypes.ts, dbmongo/js/reduce.algo2/effectifs.ts, dbmongo/js/reduce.algo2/effectifs_tests.ts, dbmongo/lib/engine/jsFunctions.go
Effectué en pair coding avec Pierre:
- écriture de test unitaires pour `effectifs.ts`
=> tests(reduce.algo2): Écriture de tests unitaires pour `effectifs.ts`

dbmongo/lib/bdf/main.go
=> refactor(BDF): Encapsulation de la partie pure du parseur BDF

dbmongo/lib/ellisphere/main.go
Même démarche que dans PR #174, pour harmoniser le comportement des parseurs. Contribue à #167.
Tes idées/suggestions sont les bienvenues, dans cette démarche d'harmonisation !
Les fondements de cette harmonisation sont les suivants:
- un parseur = une fonction pour itérer sur les fichiers + une fonction pour traiter un fichier + une fonction pour traiter chaque ligne
- faire en sorte que chaque fonction n'accède qu'à ce dont elle a vraiment besoin, afin de simplifier l'écriture de tests
- objectif à terme: harmoniser le fonctionnement (notamment la gestion d'erreurs) des parseurs en réduisant les parties redondantes: itération sur fichiers et – au moins partiellement – le traitement de chaque fichier.
Exemple de question ouverte sur laquelle j'aimerais ton avis: est-il important de …
=> fix(ellisphere): Refactoring du parseur "ellisphere"

dbmongo/lib/engine/main.go
=> fix(tests): Tri des erreurs de parsing pour reproductibilité des rapports

dbmongo/lib/apconso/main.go, dbmongo/lib/apdemande/main.go
Effectué en pair coding avec Pierre.
=> fix: Harmonisation des parseurs

dbmongo/lib/apconso/testData/expectedApconso.json, dbmongo/lib/apdemande/testData/expectedApdemande.json, dbmongo/lib/bdf/testData/expectedBdfOutput.json, dbmongo/lib/diane/testData/expectedDiane.json, dbmongo/lib/ellisphere/testData/expectedEllisphere.json, dbmongo/lib/engine/event.go, dbmongo/lib/marshal/event.go, dbmongo/lib/marshal/parser.go, dbmongo/lib/marshal/tracker.go, dbmongo/lib/reporder/testData/expectedReporder.json, dbmongo/lib/sirene/testData/expectedSirene.json, dbmongo/lib/sirene_ul/testData/expectedSireneUL.json, dbmongo/lib/urssaf/testData/expectedCcsf.json, dbmongo/lib/urssaf/testData/expectedCotisation.json, dbmongo/lib/urssaf/testData/expectedDebit.json, dbmongo/lib/urssaf/testData/expectedDebitCorrompu.json, dbmongo/lib/urssaf/testData/expectedDelai.json, dbmongo/lib/urssaf/testData/expectedEffectif.json, dbmongo/lib/urssaf/testData/expectedEffectifEnt.json, dbmongo/lib/urssaf/testData/expectedProcol.json, tests/output-snapshots/test-api-check.golden.txt, tests/output-snapshots/test-api-import.golden.txt, tests/test-api-check.sh, tests/test-api-import.sh
Fixes #219, #220.
Effectué en pair avec @vviers.
=> fix: Changement de structure des logs de parseurs

dbmongo/lib/engine/adminBatch.go, dbmongo/lib/engine/event.go, dbmongo/lib/marshal/event.go, tests/output-snapshots/test-api-check.golden.txt, tests/output-snapshots/test-api-import.golden.txt, tests/test-api-check.sh, tests/test-api-import.sh
=> feat(journal): Garder une trace de l'API qui a produit chaque rapport

tools/logsReport/README.md
=> doc: update dependencies for linux users

js/RawDataTypes.ts, js/reduce.algo2/fraisFinancier_tests.ts
Suite de PR #291.
Cf discussion avec Christophe: https://github.com/signaux-faibles/opensignauxfaibles/pull/291#discussion_r560159003.
=> fix(TS): Les clés Diane ne peuvent être null

lib/marshal/fields.go, lib/urssaf/debit.go, lib/urssaf/effectif.go, lib/urssaf/effectif_ent.go, lib/urssaf/procol.go, lib/urssaf/urssaf_test.go
=> fix(parsers): Harmonisation de l'indexation de colonnes dans les parseurs procol et effectif

lib/marshal/mapping.go, lib/marshal/mapping_test.go
=> fix(parsers): Harmonisation de l'indexation de colonnes du parseur de comptes URSSAF

lib/engine/event.go, lib/engine/reduce.go, tests/output-snapshots/test-reduce.golden.json, tests/test-reduce.sh
=> feat(Journal): Préciser batchId dans chaque rapport de Reduce

js/GeneratedTypes.d.ts, lib/ellisphere/main.go, lib/engine/validationSchemas.go, validation/ellisphere.schema.json
Je ne suis pas 100% de mon mapping entre les champs de fichiers Ellisphere et la documentation fournie par email, mais voici une proposition. Je me suis également appuyé sur le fichier de test fourni avec le parseur.
J'en ai profité pour aligner les tags des champs du type struct `Ellisphere` défini dans le parseur.
=> doc(variables): Documentation des champs Ellisphere

.gitignore, .vscode/extensions.json
Le fichier `.vscode/extensions.json` permet de suggérer aux utilisateurs de VSCode d'installer les extensions suivantes pour améliorer leur expérience de développement sur `opensignauxfaibles`:
- [`golang.go`](https://marketplace.visualstudio.com/items?itemName=golang.Go) affiche les problèmes de syntaxe dans le code Go, entre autres intégrations d'outils Go (formatage, etc...)
- [`dbaeumer.vscode-eslint`](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint) affiche les problèmes de syntaxe dans le code JS/TS et suggère des correctifs
- [`esbenp.prettier-vscode`](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) permet de formater le code (et autres fichiers, dont Markdown, JSON, etc...) automatiquement, en respectant les préférences …
=> fix(vscode): Suggestion d'extensions pour les utilisateurs de Visual Studio Code

lib/engine/adminBatch.go, lib/engine/data.go, lib/engine/db.go, lib/engine/event.go, lib/engine/js/loadJS.go, lib/engine/public.go, lib/engine/purgeBatch.go, lib/engine/reduce.go, lib/marshal/mapping.go, lib/marshal/parser_test.go, lib/marshal/testing.go, main.go, main_test.go, parseFileHandler.go, validation/validation.go
Juste une proposition que j'avais gardé de côté pour plus tard: normaliser les logs, dont remplacement des `panic` par des `log.Fatal()`.
Certaines questions restent ouvertes, cf commentaires dans le code.
=> fix: Normalisation des logs
