.gitignore, dbmongo/js/test/test_map_reduce_algo2.js, dbmongo/js/test/test_map_reduce_algo2.sh
Début de test de bout en bout des fonctions du map reduce algo2. 
Le test nécessite l'accès à des données anonymisées mais confidentielles.  
TODO: 
- Refacto: définir toutes les fonctions de substitution (ISODate, NumberInt) dans le fichier js. 
- Refacto: Retirer les appels à "cat" et faire un one liner "jsc"
- Fix: jsc retourne "Invalid Date" sous MacOSX à la commande: 
`new Date("2016-03-01T00:00:00.000+0000")`
=> Début de test de bout en bout des fonctions du map reduce algo2

dbmongo/js/test/test_map_reduce_algo2.js, dbmongo/js/test/test_map_reduce_algo2.sh
Adresse les TODOs listés dans PR #4: 
`new Date("2016-03-01T00:00:00.000+0000")`
=> fix(test): Corrige les valeurs `null` de `effectifs`, sur macos

.github/workflows/go.yml
Suite de PR #13.
Note: une seule relecture/validation de cette PR devrait suffire.
=> fix(ci): Plus besoin de copier jsFunctions.go dans GOPATH

README.md, dbmongo/lib/marshal/generateParser.go, dbmongo/lib/marshal/parserSpecs/apdemande.yaml
Problème réglé par cette PR:
```
$ cd dbmongo
$ go generate -x ./...
[...]
go run generateParser.go
2020/04/28 11:41:55 File could not be read: yaml: line 19: block sequence entries are not allowed in this context
exit status 1
lib/marshal/readOptions.go:14: running "go": exit status 1
```
=> fix: Erreur de génération de parseur 

dbmongo/go.mod, dbmongo/go.sum
Lorsqu'on lance les tests, les dépendances de test sont ajoutées à go.mod et go.sum. 
Je propose d'intégrer ces dépendances au go.mod, il semblerait que c'est la manière de procéder: 
https://github.com/golang/go/issues/26913
Fil intéressant également sur comment identifier les dépendences de test dans un module go: 
https://github.com/golang/go/issues/26955
PS: En fait je ne suis pas sûr de comprendre exactement ce qu'il se passe dans le go.sum, qui avait déjà des lignes pour testify et go-difflib...
=> fix: ajout des dépendances de test au module

dbmongo/lib/diane/main.go, dbmongo/lib/marshal/testing.go
Fixes #11.
Les erreurs de syntaxe du script `awk` de `convert_diane.sh` ne sont pas remontées lors de l'exécution des tests du parseur Diane.
Exemple d'erreur non rapportée (cas réel: https://github.com/signaux-faibles/opensignauxfaibles/issues/11#issuecomment-620060414):
```
$ sh convert_diane.sh testData/dianeTestData.txt
awk: line 15: syntax error at or near ,
```
- refactorisation du parseur Diane pour rendre sa logique plus lisible et clarifier la gestion d'erreurs
- créer des évènements `debug` pour chaque ligne retournée par `convert_diane.sh` dans la sortie standard d'erreurs
- le test consomme et affiche les évènements produits par le parseur
- le teste échoue si une erreur critique a été interceptée
1. Dans `convert_diane.sh`, ajouter une ligne `fai{l` juste avant le `BEGIN {` …
=> fix: Rapport d'erreurs de convert_diane.sh

dbmongo/js/test/test_algo2.sh, dbmongo/js/test/test_common.sh, dbmongo/js/test/test_compact.sh, dbmongo/js/test/test_map_reduce_algo2.sh, dbmongo/js/test/test_public.sh, dbmongo/js_test.go, test_js_functions.sh
Effectué en pair coding avec @JazzyPierrot 
Changements:
- Le test de map (`test_map_reduce_algo2`) est désormais fonctionnel: il compare la sortie avec un véritable golden file, et permet sa mise à jour
- Considération de chaque fichier sh comme un test séparé
- Affichage des logs de chaque test en cas d'echec
- Exécution séléctive avec `SKIP_ON_CI` (car la CI ne peut pas récupérer nos données de test)
TODO
=> tests: Finalisation du test de map de la phase de calculs (js)

dbmongo/lib/marshal/testing.go
Une erreur `panic: Log in goroutine after TestEffectif has completed` fait échouer les tests en CI, sur la branche `master`:
Exemple: https://github.com/signaux-faibles/opensignauxfaibles/runs/629288009
```
panic: Log in goroutine after TestEffectif has completed
goroutine 13 [running]:
testing.(*common).logDepth(0xc000312b40, 0xc00000ab00, 0xf4, 0x3)
/opt/hostedtoolcache/go/1.14.2/x64/src/testing/testing.go:680 +0x4d3
testing.(*common).log(...)
/opt/hostedtoolcache/go/1.14.2/x64/src/testing/testing.go:662
testing.(*common).Logf(0xc000312b40, 0xba115d, 0xe, 0xc000055f28, 0x2, 0x2)
/opt/hostedtoolcache/go/1.14.2/x64/src/testing/testing.go:701 +0x7e
github.com/signaux-faibles/opensignauxfaibles/dbmongo/lib/marshal.TestParserTupleOutput.func1(0xc000310540, 0xc000312b40, 0xc000010098) …
```
=> fix(tests): Libérer la goroutine d'affichage d'évènements

dbmongo/js_test.go, dbmongo/lib/engine/js/loadJS.go, dbmongo/lib/engine/typescript.go
Problème: le développeur pourrait croire à tort que ses modifs sur les fichiers `.ts` fonctionnent si les tests passent, alors qu'il a oublié d'exécuter `go generate` pour les transpiler...
Solution proposée: `go test` lancera systématiquement la transpilation.
=> tests: Transpiler les fichiers TypeScript lors de l'exécution des tests JS

dbmongo/lib/diane/main.go
Suite à discussion avec Christophe, concernant l'usage de `event` et `tracker` dans [parseur diane](https://github.com/signaux-faibles/opensignauxfaibles/pull/20):
- utiliser `tracker` seulement pour les erreurs qui arrivent en cours de progression (afin de bénéficier d'un rapport standardisé de parsing). pour les autres erreurs: `event.Critical("")` suffit
- laisser l'appelant décider si on `abort` ou pas => remplacer `return true` par `return error("")`
=> fix(refactor): Restructuration du parseur Diane et simplification de gestion d'erreurs

.github/workflows/go.yml
Nous avons vu récemment qu'il n'était plus nécéssaire d'exécuter `go get` pour récupérer les dépendances depuis que dbmongo est un Go Module.
Cette PR propose de retirer cette étape de notre workflow d'intégration continue, dans l'espoir de l'accélérer un peu.
Cf https://github.com/signaux-faibles/opensignauxfaibles/actions pour comparer les durées.
=> feat(ci): Dépendances téléchargées à la demande

dbmongo/js/reduce.algo2/apart.js, dbmongo/js/reduce.algo2/finalize_test.js, dbmongo/js/reduce.algo2/fraisFinancier.js, dbmongo/js/reduce.algo2/fraisFinancier.ts, dbmongo/js/reduce.algo2/fraisFinancier_tests.ts, dbmongo/js/reduce.algo2/map.js, dbmongo/js/reduce.algo2/map_test.js, dbmongo/js/test/helpers/fakes.js, dbmongo/js/test/test_algo2.sh, dbmongo/js/test/test_finalize_algo2.sh, dbmongo/js/test/test_map_algo2.sh, dbmongo/lib/engine/js/loadJS.go, dbmongo/lib/engine/jsFunctions.go, dbmongo/lib/engine/typescript.go
Travail effectué avec Pierre:
- Écriture de deux test unitaires exprimés en français (pour servir de documentation des fonctions de calcul) pour `fraisFinancier.js`
- Conversion de `fraisFinancier.js` au format TypeScript
- Harmonisation de la manière d'exporter les modules JS, et d'ignorer cette exportation depuis `jsLoad.go`
- Harmonisation du formatage de `jsFunctions.go`
- Laisser `fakes.js` initialiser les variables globales `f` et `exports`
- Déplacement du `"use strict"` dans `apart.js`, pour éviter erreur à l'exécution par mongodb
=> fix(TS): Passage de fraisFinancier.js en TypeScript + test

dbmongo/js/package-lock.json, dbmongo/js/package.json, dbmongo/js/reduce.algo2/map_tests.ts, dbmongo/js/tsconfig.json
- Usage de `ava` seul avec une configuration TypeScript (nécessaire) au lieu de `ava-ts`.
- Désactivation de vérifications et chargements de fichiers inutiles à la bonne exécution de `npm test`.
=> l'exécution des tests (`npm test`) dure 1,20 secondes au lieu de 3,20.
=> fix(tests): Optimisation des tests TypeScript

test-api.golden-master.txt, test-api.sh
Problème: les résultats des tests de bout en bout sont trop peu lisibles pour détecter et investiguer les différences qui pourraient apparaitre.
Solution: cette PR formate les résultats JSON de manière à ce que chaque propriété soit affiché sur une ligne dédiée.
Bonus: ce formatage rend plus simple le filtrage des logs, et donc le script d'exécution des tests.
=> fix(tests): Formatage JSON dans tests de bout en bout

dbmongo/js/common/generatePeriodSerie.d.ts, dbmongo/js/common/setBatchValueForType.ts, dbmongo/js/compact/complete_reporder.ts, dbmongo/js/compact/currentState.ts, dbmongo/js/compact/reduce.ts, dbmongo/js/compact/reduce_test.js, dbmongo/js/globals.ts, dbmongo/js/package.json, dbmongo/js/reduce.algo2/delais.ts, dbmongo/js/reduce.algo2/delais_tests.ts, dbmongo/js/reduce.algo2/fraisFinancier.ts, dbmongo/js/reduce.algo2/fraisFinancier_tests.ts, dbmongo/js/reduce.algo2/map.d.ts, dbmongo/js/test/test_compact.sh, dbmongo/js/tsconfig.json, dbmongo/lib/engine/jsFunctions.go
Avec la configuration TypeScript actuelle, il reste possible que nous ne soyons pas alertés si nous passons un objet incomplet (ex: contenant des propriétés `null` ou `undefined`) à une fonction dans laquelle nous aurions oublié de définir le type des paramètres.
Or on souhaite justement éviter que ce genre de cas entrainent une erreur en runtime après des heures de calculs !
Activer `noImplicitAny` dans la configuration de TypeScript permet de nous forcer à typer explicitement tous les paramètres et les retours de nos fonctions, et donc à activer la validation de ces types (et notamment vérifier que les propriétés non optionnelles soient fournies) dans toutes nos fonctions, y compris les fonctions que nous n'avons pas encore passé en TypeScript. (grâce à l'ajout de fichiers de …
=> fix(TS): Sécurisation des fonctions TS (`noImplicitAny`)

dbmongo/js/public/apconso.d.ts, dbmongo/js/public/apconso.js, dbmongo/js/public/ava_tests.ts, dbmongo/js/public/compte.d.ts, dbmongo/js/public/compte.js, dbmongo/js/public/cotisations.d.ts, dbmongo/js/public/cotisations.js, dbmongo/js/public/dealWithProcols.d.ts, dbmongo/js/public/dealWithProcols.js, dbmongo/js/public/debits.d.ts, dbmongo/js/public/debits.js, dbmongo/js/public/delai.d.ts, dbmongo/js/public/delai.js, dbmongo/js/public/effectifs.d.ts, dbmongo/js/public/effectifs.js, dbmongo/js/public/finalize.d.ts, dbmongo/js/public/finalize.js, dbmongo/js/public/flatten.d.ts, dbmongo/js/public/flatten.js, dbmongo/js/public/iterable.d.ts, dbmongo/js/public/iterable.js, dbmongo/js/public/map.d.ts, dbmongo/js/public/map.js, dbmongo/js/public/reduce.d.ts, dbmongo/js/public/reduce.js, dbmongo/js/public/sirene.d.ts, dbmongo/js/public/sirene.js
Suite de PR #60. Démarche similaire à PR #60, appliquée au calcul de `public`.
Nous avons bien avancé sur le typage des donnés manipulées par les fonctions TS/JS, mais rien ne nous prouve que les valeurs passées par MongoDB d'un étape à une autre (c.a.d. `map()` --> `reduce()` --> `finalize()`) respectent ces types dans tous les cas, car MongoDB ne voit pas nos types. Notamment depuis les modifs proposées dans PR #59.
=> Risque: les traitements "compact", "reduce" et "public" risquent toujours d'échouer après des heures de calculs.
Ajout d'une suite de tests d'intégration en TypeScript pour vérifier la compatibilité des types et mesurer la couverture lors du passage de données entre les fonctions `map()`, `reduce()` et `finalize()`, en s'appuyant sur le jeu de données minimal utilisé dans …
=> tests(TS): Tests d'integration pour fonctions map/reduce/finalize de `public`

dbmongo/js/compact/ava_tests.ts, dbmongo/js/compact/currentState.ts, dbmongo/js/compact/reduce.ts, dbmongo/js/reduce.algo2/fraisFinancier_tests.ts, dbmongo/js/test/test_algo2.sh, dbmongo/js/test/test_common.sh, dbmongo/js/test/test_compact.sh, dbmongo/js/test/test_finalize_algo2.sh, dbmongo/js/test/test_map_algo2.sh, dbmongo/js/test/test_public.sh, dbmongo/js/tsconfig-transpilation.json, dbmongo/js/tsconfig.json, dbmongo/lib/engine/jsFunctions.go, dbmongo/lib/engine/typescript.go
Objectif: sécurisation encore plus stricte du code JS/TS, pour réduire le risque d'interruption après des heures de calculs.
- activation de `strictFunctionTypes` dans `tsconfig.json`
- correction des scripts, majoritairement: cesser de forcer le type du paramètre passé par `forEach`
- application des flags de tsconfig aux tests ava, pour voir les erreurs depuis l'IDE (au lieu de les découvrir à l'exécution, avec des numéros de lignes incorrects)
- introduction de `tsconfig-transpilation.json` pour éviter que les tests ava ne soient transpilés puis importés dans `jsFunctions.go` lors de l'appel à `go generate`
```sh
$ cd dbmongo
$ (cd lib/engine && go generate .) && \
(cd js && npm run lint && npm test) && \
go test && \
(killall dbmongo; go build) && \
(cd .. && ./test-api.sh)
```
=> fix(TS): Activation de strictFunctionTypes

test-all.sh
Problème: `go test` n'exécute que les tests unitaires et d'intégration, mais pas les tests de bout en bout. (`test-api.sh` et `test-api-2.sh`) => Tout breaking change non détecté par les tests unitaires et d'intégration ne serait découvert qu'au moment du passage en CI, c'est à dire trop tard quand on est en plein développement.
Workaround appliqué jusqu'à présent: j'inclue le contenu de ce script dans la description de chaque PR.
Proposition: ajouter le script `test-all.sh` à la racine du projet pour exécuter `go test` et les tests de bout en bout. En profiter pour exécuter le linter et les tests JS avant de lancer ceux-ci. (car ces premiers sont plus rapides => gain de temps en cas d'erreur JS, en tout cas pour l'instant)
Comment tester:
```sh
$ ./test-all.sh
```
=> tests: Ajout d'un script pour exécuter tous les tests, y compris de bout en bout

dbmongo/data.go, dbmongo/handlers.go, dbmongo/js/compact/reduce.ts, dbmongo/lib/engine/adminBatch.go, dbmongo/lib/engine/data.go, dbmongo/lib/engine/jsFunctions.go
Effectué en pair coding avec Pierre.
Tel qu'exprimé lors de la revue d'une précédente PR (https://github.com/signaux-faibles/opensignauxfaibles/pull/66/files/cc13e6f1c3ccca69a52ebf9d6a126ea1086264e8#r442061422): le paramètre `types` avait été introduit dans l'API `compact` pour un besoin ponctuel, et la complexité qu'il apporte pourrait augmenter le risque d'ajout de bugs.
- retrait du paramètre `types` dans le code Golang
- simplification de l'algorithme JS => retrait des variables `types`, `new_types` et `all_interesting_types` devenues inutiles
=> refactor(compact): Suppression du paramètre `types` désormais inutile

test-api.sh
...car les flags de `sed` ne sont pas compatibles entre Linux et Darwin/macOS => `test-api.sh` l'employait différemment en fonction de l'environnement d'exécution.
=> fix(scripts): Remplacer `sed -i ''` par `perl -pi'' -e`

dbmongo/js/compact/ava_tests.ts, dbmongo/js/globals.ts, dbmongo/js/public/effectifs.d.ts, dbmongo/js/reduce.algo2/apart.ts, dbmongo/js/reduce.algo2/ccsf.ts, dbmongo/js/reduce.algo2/compte.ts, dbmongo/js/reduce.algo2/cotisation.ts, dbmongo/js/reduce.algo2/cotisationsdettes.ts, dbmongo/js/reduce.algo2/dealWithProcols.ts, dbmongo/js/reduce.algo2/defaillances.ts, dbmongo/js/reduce.algo2/delais.ts, dbmongo/js/reduce.algo2/delais_tests.ts, dbmongo/js/reduce.algo2/effectifs.ts, dbmongo/js/reduce.algo2/finalize.ts, dbmongo/js/reduce.algo2/flatten.ts, dbmongo/js/reduce.algo2/interim.ts, dbmongo/js/reduce.algo2/map.ts, dbmongo/js/reduce.algo2/outputs.ts, dbmongo/js/reduce.algo2/populateNafAndApe.ts, dbmongo/js/reduce.algo2/repeatable.ts, dbmongo/js/reduce.algo2/sirene.ts, dbmongo/js/reduce.algo2/sirene_ul.ts, dbmongo/lib/engine/jsFunctions.go
Uniformisation des types de `reduce.algo2`:
- extraire types `DonnéesXxx` et `EntréeXxx` puis les employer dans la définition de `BatchValue`, cf https://github.com/signaux-faibles/opensignauxfaibles/pull/78#discussion_r444970708
- renommer types de sortie de chaque fonction en `SortieXxx`, cf https://github.com/signaux-faibles/opensignauxfaibles/pull/78#discussion_r444885053
Prochaine étape: je propose de travailler sur les TODOs introduits par cette PR, et nous traiterons ensemble ceux pour lesquels je n'aurai pas trouvé de solution satisfaisante.
=> fix(TS): Homogénéisation des types Données*, Entrée* et Sortie*

dbmongo/js/tsconfig.json
Problème: nos éditeurs de code (nvim et vscode) rapportaient une erreur d'importation à la ligne `import test from "ava"` présente dans tous nos tests.
Solution: dire à TypeScript que ce genre d'importations sont des modules Node.js, pour qu'il puisse trouver les types associés dans `node_modules`.
=> fix(TS): Erreur d'importation de Ava rapportée par IDE

dbmongo/js/globals.ts, dbmongo/js/reduce.algo2/delais.ts, dbmongo/js/reduce.algo2/delais_tests.ts, dbmongo/js/reduce.algo2/map.ts, dbmongo/js/reduce.algo2/nbDays.ts, dbmongo/lib/engine/jsFunctions.go
Effectué en pair coding avec @JazzyPierrot.
Propriétés renommées, en sortie d'algo2:
- `delai` --> `delai_nb_jours_restants`
- `duree_delai` --> `delai_nb_jours_total`
- `ratio_dette_delai` --> `delai_deviation_remboursement`
- `montant_echeancier` --> `delai_montant_echeancier`
=> Décision: nous allons désormais préfixer toutes les propriétés calculées à l'aide du nom de la fonction qui les a calculées.
Prochaines étapes: indiquées par des TODO dans le code + des commentaires sur le PR.
=> fix(algo2): Passage des délais en jours

dbmongo/data.go, dbmongo/js/compact/ava_tests.ts, dbmongo/js/compact/compactBatch.ts, dbmongo/js/compact/reduce.ts, dbmongo/js/compact/reduce_test.js, dbmongo/lib/engine/data.go, dbmongo/lib/engine/jsFunctions.go, test-api.sh
Problèmes:
- Pierre et moi aurions aimé renommer nos variables locales d'itération `batch` en `batchKey`, pour améliorer la lisibilité du code JS/TS de `compact`;
- Or, `batchKey` est le nom de la variable globale passée à nos fonctions par l'API `compact`, transmise par le paramètre d'API `batch=xxx`.
- Enfin, il s'avère que nous pourrions être plus précis dans le nommage de ce paramètre, pour non seulement décrire la nature de sa valeur (batch key) mais aussi l'impact de cette valeur sur le processus de traitement de données. (`from` indiquant que le compactage sera effectué *à partir* de ce batch key)
Solution: renommer la variable globale `batchKey` et le paramètre API `batch` correspondant en `fromBatchKey`.
=> fix(compact): Renommage paramètre batch / batchKey --> fromBatchKey

dbmongo/js/reduce.algo2/cotisationsdettes.ts, dbmongo/js/reduce.algo2/delais.ts, dbmongo/js/reduce.algo2/delais_tests.ts, dbmongo/js/reduce.algo2/map.ts, dbmongo/js/reduce.algo2/outputs.ts, dbmongo/lib/engine/jsFunctions.go
Changements effectués en pair avec Pierre:
- `montant_part_ouvriere` et `montant_part_patronale` ne sont désormais plus optionnels en entrée de `delais()`
- `map()` passe le retour de `cotisationsdettes()` + l'intervalle de traitement à `delais()`
- harmonisation du type `DonnéesAgrégées`
- documentation des fonctions modifiées et de leurs propriétés
- bonus: retrait de 3 `TODO`s + quelques optimisations de perf 🎉
=> fix(reduce.algo2): Calcul des montants de cotisations avant appel à delais()

dbmongo/js/globals.ts, dbmongo/js/reduce.algo2/algo2_tests.ts, dbmongo/js/reduce.algo2/flatten.ts, dbmongo/js/reduce.algo2/map.ts
Lors de l'implémentation du correctif #93, nous n'avions pas ajouté de test mettant en lumière le fait que la variable `delai_deviation_remboursement` n'était pas calculée comme prévu, lorsque qu'une dette avec demande de délai était fournie.
Le but de cette PR est de fournir ce test. Celui-ci passe sur la version actuelle de `master`, mais pas avant la fusion de PR #93.
Bonus: retrait d'un type redondant + renommage d'un type ambigu.
1. Revenir au commit https://github.com/signaux-faibles/opensignauxfaibles/commit/a0007680bc8046d16575b72df0b78351124ad44b (avant fusion de PR #93)
2. Remplacer `js/reduce.algo2/algo2_tests.ts` par la version apportée dans cette PR
3. Exécuter `$ npx ava reduce.algo2/algo2_tests.ts` => le test devrait échouer
Résultat:
=> tests(reduce.algo2): Test de non régression sur calcul de delai_deviation_remboursement

test-api-2.sh, test-api.sh
... en cachant le diff résultant de l'exécution des tests de bout en bout, souvent très volumineux et peu utiles lorsque ceux-ci échouent.
=> fix(tests): Rendre les erreurs d'API plus visibles 

dbmongo/js/globals.ts, dbmongo/js/reduce.algo2/apart.ts, dbmongo/js/reduce.algo2/cotisation.ts, dbmongo/js/reduce.algo2/cotisationsdettes.ts, dbmongo/js/reduce.algo2/cotisationsdettes_tests.ts, dbmongo/js/reduce.algo2/dealWithProcols.ts, dbmongo/js/reduce.algo2/effectifs.ts, dbmongo/js/reduce.algo2/lookAhead.ts, dbmongo/js/reduce.algo2/map.ts, dbmongo/lib/engine/jsFunctions.go
Cette PR fait suite à PR #94.
Effectué partiellement en pair coding avec @JazzyPierrot, le Lundi 13 Juillet 2020.
=> fix(reduce.algo2): Suite du refactoring de cotisationsdette + simplification des tris

dbmongo/js/reduce.algo2/effectifs.ts, dbmongo/lib/engine/jsFunctions.go
Volonté initiale: améliorer le nom et le type du paramètre `effectif_name` de la fonction `effectifs` pour rendre plus explicite le fait que cette fonction peut s'appliquer à la fois aux entreprises et aux établissements – contrairement à la plupart des autres fonctions de calcul.
Problèmes sous-jacents: ils s'avère que tous les types de cette fonction – notamment le type des données en sortie – manquaient de précision.
=> fix(reduce.algo2): Renommage et explicitation des types dans effectifs()

dbmongo/js/common/omit.ts, dbmongo/js/globals.ts, dbmongo/js/reduce.algo2/cotisationsdettes_tests.ts, dbmongo/js/reduce.algo2/entr_bdf.ts, dbmongo/js/reduce.algo2/entr_sirene.ts, dbmongo/js/reduce.algo2/map.ts, dbmongo/lib/engine/jsFunctions.go
Effectué en pair coding avec @JazzyPierrot:
- Extraction de fonction `entr_bdf()` depuis le `map()` de `reduce.algo2`
- Réutilisation de `omit()` => déplacement dans `common/`
- Uniformisation du nommage de fichiers et types pour fonctions de calcul s'appliquant aux entreprises
- Explicitation et documentation de types Bdf
Next steps (dans PR séparée(s)):
- cf questions en commentaires de cette PR
- ajout d'un test unitaire pour éviter regressions silencieuses en CI (cf https://github.com/signaux-faibles/opensignauxfaibles/pull/101#issuecomment-661844701 et https://github.com/signaux-faibles/opensignauxfaibles/pull/101#issuecomment-661978167)
- et TODOs
=> fix(reduce.algo2): Extraction de entr_bdf()

dbmongo/js/reduce.algo2/entr_sirene.ts, dbmongo/js/reduce.algo2/map.ts, dbmongo/lib/engine/jsFunctions.go
Comme suggéré dans https://github.com/signaux-faibles/opensignauxfaibles/pull/101#discussion_r458234857, et similairement à la signature de `entr_bdf`, passer `v.sirene_ul` à `f.entr_sirene`, au lieu de `v` pour éviter d'avoir à convertir/forcer le type de `v` lors de l'appel depuis `map()`.
J'en ai profité pour aller un poil plus loin dans le refactoring de `f.entr_sirene()` et la partie "entreprise" de `f.map()`:
- rendre `entr_sirene()` pure, en m'inspirant de notre travail sur `entr_bdf()`
- retrait de `output_array` => `output_indexed` devient l'unique source de vérité.
=> fix(reduce.algo2): Simplification de la signature de entr_sirene()

dbmongo/data.go, tests/test-api-export.sh
Cf https://github.com/signaux-faibles/opensignauxfaibles/pull/105#issuecomment-663031077
Les APIs `GET /api/data/entreprises` et `GET /api/data/etablissements` peuvent filtrer les résultats par numéro SIREN d'entreprise (9 chiffres), via le paramètre `key` (optionnel), et retourner une erreur en cas de valeur invalide.
```sh
$ (killall dbmongo; cd dbmongo && go build) && tests/test-api-export.sh
```
=> fix(export): Paramètre `key` doit être un SIREN valide

tests/test-api-export.sh
On macOS:
```sh
$ tests/test-api-export.sh
...
zcat: can't stat: dbmongo/dbmongo-data-export-etablissements-1598262385.json.gz (dbmongo/dbmongo-data-export-etablissements-1598262385.json.gz.Z): No such file or directory
```
https://serverfault.com/a/570026
=> fix(tests): Fichier non trouvé par test-api-export.sh, sur Mac

.github/workflows/js-functions.yml
Codacy rapportait un taux de couverture de 40% de notre code JS/TS alors que notre outil de mesure rapporte 88%.
Après une discussion avec le support technique de Codacy, il s'avère que leur analyseur ne supporte pas les rapport mélangeant plusieurs langages, et que c'est le taux de couverture du premier langage (en l'occurrence: JS) qui l'emportait.
N'envoyer le rapport de couverture que pour les fichiers TS. (soit la majorité de nos fonctions map-reduce)
=> fix(codacy): Rapporter seulement la couverture des fonctions TS

dbmongo/docs/swagger/swagger.json, dbmongo/docs/swagger/swagger.yaml, dbmongo/handlers.go, dbmongo/lib/engine/main.go, dbmongo/lib/urssaf/delai.go, tests/output-snapshots/test-api-import.golden.txt, tests/test-api-import.sh
Les erreurs `Cycle 2: Pas de siret associé au compte CCC à la période DDD` étaient listées dans la propriété `event.headFatal` de `Journal`, après la tentative d'importation d'une entrée `Delai` filtrée.
Et le rapport d'importation comptait ces erreurs comme fatales: `delaiTestData.csv: intégration terminée, 2 lignes traitées, 1 erreures fatales, 0 rejets, 0 lignes filtrées, 2 lignes valides `
Elles sont désormais listées dans `event.headFilters`, cf: https://github.com/signaux-faibles/opensignauxfaibles/pull/157/commits/80c1db20253208d65fe9d60f3e3ae19670309c1a#diff-e6c67309a010c09ce456b6447337e994R62.
=> Rapport d'importation corrigé: `delaiTestData.csv: intégration terminée, 2 lignes traitées, 0 erreures fatales, 0 rejets, 1 lignes filtrées, 2 lignes valides`
- Pour éviter les …
=> fix(import): Les erreurs de filtrage de Delai ne sont pas fatales

dbmongo/lib/base/cron.go, dbmongo/lib/engine/adminBatch.go, dbmongo/lib/engine/main.go, dbmongo/lib/marshal/parser.go, dbmongo/lib/urssaf/debit.go
Extension de PR #182.
Objectif: que la personne en charge de l'importation sache le nombre _total_ d'erreurs rencontrées pendant le parsing des fichiers d'un batch avant son importation, même si ce nombre d'erreur excède 200. (valeur de `MaxParsingErrors`)
Rendu dans la sortie standard, lors de la vérification d'un gros fichier `debit`:
```
[...]
[GIN-debug] Listening and serving HTTP on :5000
Chargement des comptes urssaf
Reading csv line 553652
Reading csv line 1361631
Reading csv line 2081958
[...]
Reading csv line 101127890
```
... et, seulement dans le cas de l'import:
```
[...]
Reading csv line 55167603
Reached 200 parsing errors => stopping.
```
Appliquer le `git patch` suivant:
```diff
diff --git a/tests/helpers/dbmongo-server.sh b/tests/helpers/dbmongo-server.sh
index …
```
=> feat(check): L'API /data/check lit chaque fichier jusqu'à la fin

dbmongo/js/compact/reduce.ts, dbmongo/lib/engine/jsFunctions.go
Problème: `severalBatches` est vrai même si on a qu'un seul batch réparti entre deux 2 documents `ImportedData`. (comme vu dans le test de PR #217.
Ce défaut empêche `reduce()` de se terminer de manière anticipée.
=> fix(compact): Optim sur compactage d'un batch couvert par 2 documents

.github/workflows/e2e.yml, dbmongo/js/common/forEachPopulatedProp.ts, dbmongo/js/compact/reduce_tests.ts, dbmongo/lib/engine/data.go, dbmongo/lib/engine/data_validation.go, dbmongo/validation/detect_invalid_entries.pipeline.json, test-all.sh, tests/test-api-compact-failure.sh
cf https://github.com/signaux-faibles/opensignauxfaibles/issues/211#issuecomment-713539433
Tel que décrit dans #211, une opération de compactage en production a été interrompue prématurément avec un message d'erreur javascript `can't convert undefined to object`.
Après quelques recherches, il s'avère que ce cas peut arriver quand le `reduce()` de l'API `/compact` s'applique sur un batch contenant une entrée de données de type `undefined` (au lieu de `object`).
Afin d'éviter que cette erreur ne puisse se produire à nouveau, j'ai ajouté une agrégation MongoDB dans l'API `/validate` qui retourne tout document de `ImportedData` ou `RawData` contenant une entrée `undefined`. => Je suggère qu'on appelle cette API sur les collections `ImportedData` et `RawData` avant de lancer un compactage. …
=> fix(compact): Détection d'entrée `undefined` en db pour prévenir interruption de compactage

dbmongo/lib/bdf/main.go, dbmongo/lib/bdf/main_test.go, dbmongo/lib/ellisphere/main.go, dbmongo/lib/marshal/filter.go, dbmongo/lib/marshal/filter_test.go, dbmongo/lib/marshal/mapping.go, dbmongo/lib/marshal/mapping_test.go, dbmongo/lib/reporder/reporder.go, dbmongo/lib/sirene/main.go, dbmongo/lib/sirene_ul/main.go, dbmongo/lib/urssaf/effectif.go, dbmongo/lib/urssaf/effectif_ent.go, dbmongo/lib/urssaf/urssaf_test.go
Afin de faciliter l'utilisation et l'amélioration du Filtre d'entreprises dans les parseurs:
- encapsulation de la `map` dans un type dédié `SirenFilter`
- association des fonctions `IsFiltered()` et `Includes()` (anciennement `FilterHas()`) comme méthodes de ce type
- clarification de la documentation de ces méthodes
- correction d'un bug rencontré pendant le refactoring: le filtre ne s'appliquait pas aux données `Effectif` 😓 
- => ajout d'un test de non régression: "Effectif n'est importé que si inclus dans le filtre"
- ne plus valider le SIRET/SIREN au moment à chaque interrogation du filtre => laisser cette responsabilité à l'appelant => supprimer `IsFiltered()`, au profit de `Includes()`
- optimiser l'interrogation du filtre
=> fix: Refonte du filtrage SIREN d'entreprises + correction Effectif

dbmongo/lib/bdf/main.go, dbmongo/lib/ellisphere/main.go, dbmongo/lib/ellisphere/testData/expectedEllisphere.json, dbmongo/lib/marshal/filter.go, dbmongo/lib/marshal/filter_test.go, dbmongo/lib/marshal/mapping.go, dbmongo/lib/reporder/reporder.go, dbmongo/lib/sfregexp/regexp.go, dbmongo/lib/sirene/main.go, dbmongo/lib/sirene_ul/main.go, dbmongo/lib/urssaf/effectif.go, dbmongo/lib/urssaf/effectif_ent.go, tests/output-snapshots/test-api-import.golden.txt
Suite de #222.
Next:
- Appliquer `SirenFilter` sur les tuples retournés par tous les parseurs, à un seul endroit.
=> fix(filter): Retrait de IsFiltered() => validation siret/siren déléguée à l'appelant

dbmongo/lib/apconso/main.go, dbmongo/lib/apdemande/main.go, dbmongo/lib/bdf/main.go, dbmongo/lib/diane/main.go, dbmongo/lib/ellisphere/main.go, dbmongo/lib/marshal/parser.go, dbmongo/lib/marshal/testing.go, dbmongo/lib/reporder/reporder.go, dbmongo/lib/sirene/main.go, dbmongo/lib/sirene_ul/main.go, dbmongo/lib/urssaf/ccsf.go, dbmongo/lib/urssaf/compte.go, dbmongo/lib/urssaf/cotisation.go, dbmongo/lib/urssaf/debit.go, dbmongo/lib/urssaf/delai.go, dbmongo/lib/urssaf/effectif.go, dbmongo/lib/urssaf/effectif_ent.go, dbmongo/lib/urssaf/procol.go
Suite de PR #225.
Inspiré par une suggestion de Pierre, cette PR exposer la méthode `ParseLines()` via une interface au lieu de la retourner comme propriété d'une structure.
=> fix(parseurs): Chaque parseur implémente l'interface Parser

dbmongo/lib/apconso/main.go, dbmongo/lib/apdemande/main.go, dbmongo/lib/base/errors.go, dbmongo/lib/bdf/main.go, dbmongo/lib/diane/main.go, dbmongo/lib/ellisphere/main.go, dbmongo/lib/marshal/parser.go, dbmongo/lib/marshal/tracker.go, dbmongo/lib/reporder/reporder.go, dbmongo/lib/sirene/main.go, dbmongo/lib/sirene_ul/main.go, dbmongo/lib/urssaf/ccsf.go, dbmongo/lib/urssaf/compte.go, dbmongo/lib/urssaf/cotisation.go, dbmongo/lib/urssaf/debit.go, dbmongo/lib/urssaf/delai.go, dbmongo/lib/urssaf/effectif.go, dbmongo/lib/urssaf/effectif_ent.go, dbmongo/lib/urssaf/procol.go
Contribue à #167.
- les parseurs pouvaient rapporter n'importe quelle erreur, en oubliant de spécifier un niveau de criticité
- les erreurs sans niveau de criticité étaient rapportées comme `fatal` par défaut, alors qu'on souhaite éviter de découvrir ce genre d'erreurs lors de l'importation de données
Pour éviter de se retrouver avec des erreurs `fatal` à cause d'oublis dans l'implémentation de parseurs, empêcher le développeur de rapporter des erreurs sans niveau de criticité.
Encapsulation cachée de `gournal.Tracker` dans `ParsingTracker`, qui ne permet que l'ajout d'erreurs associées à un niveau de criticité.
=> fix(parseurs): Imposer la qualification de chaque erreur de parsing

dbmongo/js/RawDataTypes.ts, dbmongo/js/reduce.algo2/dealWithProcols.ts, dbmongo/js/reduce.algo2/dealWithProcols_tests.ts, dbmongo/lib/engine/jsFunctions.go
- Ajout d'un test unitaire pour la fonction `dealWithProcol` qui n'était visiblement pas non plus testée par les tests de bout en bout. 
- Complétion du type "EntréeDéfaillance" avec toutes les modalités possibles. 
- Correction d'un bug (cf commentaire)
**Questions**
Est-ce qu'il y a une raison particulière de faire un alias `export type InputEvent = EntréeDefaillances` dans `reduce.algo2/dealWithProcol.ts` ? 
De même avec la fonction `defaillances` dans `reduce.algo2/defaillances.ts` qui se contente d'appeler `dealWithProcols` ?
**Étape suivante:** 
- Ajout d'un test unitaire avec ouverture puis clotûre d'une procédure collective (redressement ou sauvegarde)
=> fix: correction d'un bug dans le traitement des procédures collectives

dbmongo/lib/apconso/testData/expectedApconso.json, dbmongo/lib/apdemande/testData/expectedApdemande.json, dbmongo/lib/base/errors.go, dbmongo/lib/bdf/testData/expectedBdfOutput.json, dbmongo/lib/diane/testData/expectedDiane.json, dbmongo/lib/ellisphere/testData/expectedEllisphere.json, dbmongo/lib/marshal/mapping_test.go, dbmongo/lib/marshal/parser.go, dbmongo/lib/marshal/tracker.go, dbmongo/lib/reporder/testData/expectedReporder.json, dbmongo/lib/sirene/testData/expectedSirene.json, dbmongo/lib/sirene_ul/testData/expectedSireneUL.json, dbmongo/lib/urssaf/testData/expectedCcsf.json, dbmongo/lib/urssaf/testData/expectedCotisation.json, dbmongo/lib/urssaf/testData/expectedDebit.json, dbmongo/lib/urssaf/testData/expectedDebitCorrompu.json, dbmongo/lib/urssaf/testData/expectedDelai.json, dbmongo/lib/urssaf/testData/expectedEffectif.json, dbmongo/lib/urssaf/testData/expectedEffectifEnt.json, dbmongo/lib/urssaf/testData/expectedProcol.json, dbmongo/lib/urssaf/urssaf_test.go, tests/output-snapshots/test-api-check.golden.txt, tests/output-snapshots/test-api-import.golden.txt, tests/test-api-check.sh, tests/test-api-import.sh
Fix #210.
- Pour réduire la consommation mémoire de l'import, en cas de filtrage _agressif_: ne pas plus stocker de message d'erreur pour chaque ligne ignorée (cf tableau `headFilter` du rapport gournal)
- Bonus: ajout et réécriture de quelques tests liés au parsing
- Bonus: simplification de code redondant détecté par le linter.
=> fix(parsing): Réduction d'empreinte mémoire lors du parsing de lignes filtrées

.github/workflows/e2e.yml, dbmongo/handlers.go, dbmongo/lib/engine/data.go, dbmongo/main.go, test-all.sh, tests/test-api-prune-entities.sh
Contribue à #199.
La route `POST /api/data/pruneEntities` compte puis supprime dans la collection `RawData` les entités (établissements et entreprises) non listés dans le filtre de périmètre du batch spécifié.
```sh
http :5000/api/data/pruneEntities batch=2010 # dry-run, pour compter les entités à supprimer
http :5000/api/data/pruneEntities batch=2010 delete:=true
```
```sh
(cd dbmongo && go build) && tests/test-api-prune-entities.sh
```
=> feat(api): Comptage et suppression d'entités qui auraient du être filtrées

dbmongo/go.mod, dbmongo/go.sum, dbmongo/lib/base/errors.go, dbmongo/lib/ellisphere/testData/expectedEllisphere.json, dbmongo/lib/marshal/tracker.go, dbmongo/lib/sirene/testData/expectedSirene.json, dbmongo/lib/urssaf/debit.go, dbmongo/lib/urssaf/testData/expectedDebitCorrompu.json, tests/output-snapshots/test-api-check.golden.txt, tests/output-snapshots/test-api-import.golden.txt
Un import de données volumineuses (fichiers stock URSSAF) a échoué en production à cause d'un manque de mémoire.
L'analyse effectuée par Christophe a montré que `gournal` occupait plusieurs GO de RAM pendant l'import des fichiers.
- Afficher les avertissements liés au filtrage, au lieu de les stocker en mémoire.
- => Remplacement de `gournal` par un tracker interne.
- Bonus: afficher `Line x: ...` au lieu de `Cycle x: ...` dans le logs du Journal
- => Mise à jour des golden files
- Ne stocker que les 200 premières erreurs de parsing, au lieu de les sélectionner en fin de parsing.
- Simplification/refactoring: supprimer `lib/base/errors.go` => remplacer les fonctions `NewXxxError()` par des méthodes `AddXxxError()` au sein du `tracker`
- Puis faire en sorte qu'il soit impossible de …
=> fix: Économiser la mémoire de stockage d'erreurs de parsing

tools/logsReport/make_report.Rmd
Règle une des anomalies observées dans https://github.com/signaux-faibles/opensignauxfaibles/issues/248#issuecomment-738039462.
Les données représentées sur les graphiques de `logsReport` (tableau de bord des résultats d'import de données) n'étaient pas rangées dans l'ordre chronologique, à cause du préfixage des dates par le nom du batch.
- Spécifier l'ordre au moment de la requête `find`
- Passage du batch en suffixe, pour que `ggplot` se base bien sur la date (en début de chaine de caractères) pour effectuer son tri.
=> fix(logsReport): Ordre chronologique dans les graphiques

dbmongo/lib/apconso/testData/expectedApconso.json, dbmongo/lib/apdemande/testData/expectedApdemande.json, dbmongo/lib/bdf/testData/expectedBdfOutput.json, dbmongo/lib/diane/testData/expectedDiane.json, dbmongo/lib/ellisphere/testData/expectedEllisphere.json, dbmongo/lib/engine/adminBatch.go, dbmongo/lib/engine/event.go, dbmongo/lib/marshal/event.go, dbmongo/lib/reporder/testData/expectedReporder.json, dbmongo/lib/sirene/testData/expectedSirene.json, dbmongo/lib/sirene_ul/testData/expectedSireneUL.json, dbmongo/lib/urssaf/testData/expectedCcsf.json, dbmongo/lib/urssaf/testData/expectedCotisation.json, dbmongo/lib/urssaf/testData/expectedDebit.json, dbmongo/lib/urssaf/testData/expectedDebitCorrompu.json, dbmongo/lib/urssaf/testData/expectedDelai.json, dbmongo/lib/urssaf/testData/expectedEffectif.json, dbmongo/lib/urssaf/testData/expectedEffectifEnt.json, dbmongo/lib/urssaf/testData/expectedProcol.json
Objectif: commencer à constituer un historique des durées de traitements en prod.
Prochaines étapes: faire pareil dans les autres traitements – notamment `reduce` et `public` – qui ne stockent pour l'instant rien dans Journal.
=> feat(perf): Stockage de l'heure de début de traitement dans Journal

dbmongo/lib/engine/reduce.go, tests/test-api-reduce.sh
Avant son départ, Pierre préconisait l'usage suivant de la collection `Features` (généré par `reduce`):
- faire en sorte que seules données du dernier batch soient représentées dans `Features`, après l'appel à `reduce`
- permettre de restaurer la version précédente de ces données (ex: en cas d'incident)
Si celle-ci existe au moment de l'appel, la fonction `Reduce()` renomme désormais la collection de destination (`Features`) en employant un suffixe temporel (afin de prévenir l'écrasement de la sauvegarde précédente, en cas d'erreurs consécutives), puis la recréée lors de la fusion des résultats du map-reduce parallélisé.
Des messages sont affichés dans la sorties d'erreurs, pour informer la création de cette collection de sauvegarder, et pour inviter l'utilisateur a supprimer la …
=> feat(reduce): Sauvegarde de Features avant (re)calcul des données

dbmongo/lib/marshal/mapping_test.go, dbmongo/lib/marshal/parser.go, dbmongo/lib/urssaf/urssaf_test.go
Présence de lignes rejetées `siret invalide` dans le dernier journal d'import de `cotisation` (cf https://github.com/signaux-faibles/opensignauxfaibles/issues/248#issuecomment-738039462). Sachant que le SIRET en question est hors périmètre – et donc hors mapping de comptes URSSAF – l'entrée devrait être filtrée silencieusement, c.a.d. sans rapporter d'erreur de parsing comptée dans `nRejected` et `headRejected` du rapport de Journal.
- `runParserWithSirenFilter()` ne rapportera pas d'erreur de parsing si la ligne a été rapportée comme étant _à filtrer_.
- ajout de tests unitaires pour parseur `cotisations` et `GetSiretFromComptesMapping()`
=> fix(urssaf): Erreur "siret invalide" rapportée sur ligne hors mapping URSSAF

lib/engine/db.go, lib/engine/event.go, lib/marshal/event.go, lib/marshal/parser.go, tests/test-api-import.sh
- Plus besoin d'envoyer un message vide avant de fermer le canal d'ajout dans ImportedData (comme suggéré dans https://github.com/signaux-faibles/opensignauxfaibles/pull/266#discussion_r543672450)
- Suppression de la fonction `getBSON()` qui duplique partiellement la structure `Event` (cf PR #264)
- Suppression du type intermédiaire `engine.SocketMessage` et de ses méthodes => usage direct de `marshal.Event`
=> fix(CLI): Simplification d'usage des canaux, suite à PR #266

.gitignore, build.sh
=> build.sh est plus poli et utilise le bon nom de binaire

lib/engine/value.go, lib/sirene/main.go, lib/sirene/testData/expectedSirene.json, lib/urssaf/delai.go, lib/urssaf/testData/expectedDelai.json, tests/output-snapshots/test-import.golden.txt, tests/test-import.sh
En effet, ces hashes sont sensés rester stables, car calculés à partir du contenu de ces entrées de données.
=> Correctif: retrait des fuseaux horaires (`Europe/France`), pour que les heures parsées depuis ce fuseau soient sérialisées de manière identique en UTC, quelque soit l'environnement d'exécution des tests.
=> fix(tests): Cesser d'obfusquer les hashes résultants du test d'import

.github/workflows/js-functions.yml
Ça marche ! 🥳
... la couverture du code Golang fait baisser notre score sur Codacy 😅 – pour l'instant, en tout cas !
1. fusionner cette PR avant les autres, pour qu'on voie leur impact sur le score de couverture
2. vérifier dans [la liste des fichiers de Codacy](https://app.codacy.com/gh/signaux-faibles/opensignauxfaibles/files?bid=18037842 ) que nos fichiers Go ont désormais bien un score de couverture 
3. faire le ménage dans les workflows de CI, pour éviter d'exécuter 2 fois les tests Go.
4. augmenter la couverture, en ajoutant des tests, mais aussi en intégrant la couverture lors de l'exécution des tests de bout en bout (si possible)
=> fix(CI): Suivre aussi la couverture de tests du code Go sur Codacy

lib/apdemande/main.go, lib/apdemande/main_test.go, lib/marshal/fields.go, lib/marshal/testing.go, lib/parsing/main.go, lib/paydex/main.go, lib/paydex/main_test.go, lib/sirene/main.go, lib/sirene/main_test.go, lib/sirene_ul/main_test.go, lib/urssaf/effectif.go, lib/urssaf/effectif_ent.go, lib/urssaf/urssaf_test.go
- Dé-duplication: définir une fonction partagée pour indexer la position des colonnes de fichiers csv parsés
- Concision et documentation: spécifier les colonnes obligatoires sous forme d'annotations des champs du type de destination
- Robustesse: permettre aux parseurs de s'adapter si l'ordre des colonnes change, tout en vérifiant que les colonnes obligatoires sont bien présentes
1. J'ai repéré 3 parseurs ayant des manières différentes (mais représentatives) d'indexer et valider les colonnes attendues: `apdemande`, `sirene` / `sirene_ul`, `effectif` / `effectif_ent` et `paydex`
2. Ajouté des tests pour prévenir les regressions sur la validation de colonnes
3. Progressivement mis en places des fonctions communes pour valider et indexer les colonnes dans ces parseurs, notamment …
=> fix(parsers): Validation et indexation automatique de colonnes csv

js/RawDataTypes.ts, js/public/ava_tests.ts, js/public/map.ts, js/public/public_tests.ts, lib/engine/jsFunctions.go, lib/parsing/main.go, lib/paydex/main.go, lib/paydex/testData/expectedPaydex.json, tests/output-snapshots/test-import.golden.txt
Suite de #277.
Cette PR permet d'exporter dans la collection `Public` les données parsées depuis le fichier Paydex.
Pour que le code de cette intégration soit couvert par nos tests automatisés, et pour ne pas oublier de couvrir les entrées de données qu'on ajouterait à l'avenir, j'ai:
- introduit un type `EntrepriseBatchProps` qui – à terme – définira de manière exhaustive les entrées de données supportées par les documents de type `entreprise` stockés dans `RawData` (+ `EtablissementBatchProps` pour les `etablissement`s)
- écrit un test unitaire pour la fonction `map()` de `Public` qui créée un document `RawData` d'`entreprise` remplissant toutes les entrées supportées par ce type (défini seulement par `paydex`, pour l'instant) puis vérifie que toutes données de ces entrées se retrouvent …
=> feat(paydex): Intégrer données Paydex dans Public

.github/workflows/ci.yml
Suite à la fusion de PR #286 (sensée augmenter le score de couverture des fichiers Go), le score de couverture rapporté par Codacy a baissé de 29 points. (cf https://github.com/signaux-faibles/opensignauxfaibles/pull/286#issuecomment-757772441)
En réexécutant en local la chaine de mesure employé en CI, je me suis rendu compte que nos fichiers Go les plus couverts montraient un score très bas sur codacy (ex: [`apconso.go`](https://app.codacy.com/gh/signaux-faibles/opensignauxfaibles/file/51943291072/coverage?bid=18037842&fileBranchId=18037842) avec un score de 6%) alors que la couverture retourné par `go test` est élevée. (66%, toujours sur `apconso.go`)
Il s'avère que cette erreur de calcul est causée par l'outil `github.com/t-yuki/gocover-cobertura` employé pour générer un rapport XML …
=> fix(CI): Correction du calcul de couverture par fichier Go

lib/base/main.go, lib/marshal/mapping.go, lib/marshal/parsingHelpers.go, lib/marshal/tracker.go, lib/urssaf/ccsf.go, lib/urssaf/debit.go, lib/urssaf/delai.go, lib/urssaf/effectif.go, lib/urssaf/effectif_ent.go, lib/urssaf/procol.go, lib/urssaf/testData/expectedComptes.json, lib/urssaf/urssaf_test.go
Si un fichier urssaf est fourni avec l'extension `.gz`, `sfdata` décompressera les données à la volée, au moment de les importer.
- Ajout d'un test unitaire pour le parseur `Compte` (code: `admin_urssaf`), comme pour les autres => spécification de date de début et date de fin dans `MockBatch()`, pour que des tuples soient générés lors de l'exécution des tests => extraction de la sous-structure `adminBatchParams`
- Ajout de tests qui compressent chaque fichier de test urssaf, execute son parseur, et vérifie que la sortie correspond à celle de la version non compressée
- Ajout des helpers `OpenCsvReader()` et `OpenFileReader()` appelés dans tous les parseurs pouvant accepter des fichiers compressés avec `gzip` => déduplication du code sous-jacent.
- Tant qu'on y est: suppression des entrées …
=> feat(parsers): Les fichiers urssaf gzippés peuvent être décompressés à la volée

js/GeneratedTypes.d.ts, js/RawDataTypes.ts, js/common/procolToHuman.ts, js/compact/currentState_tests.ts, js/public/apconso.ts, js/public/apdemande.ts, js/public/map.ts, js/reduce.algo2/apart.ts, js/reduce.algo2/ccsf.ts, js/reduce.algo2/defaillances.ts, js/reduce.algo2/defaillances_tests.ts, lib/engine/data.go, lib/engine/data_validation.go, lib/engine/validationSchemas.go, validation/apconso.schema.json, validation/apdemande.schema.json, validation/ccsf.schema.json, validation/procol.schema.json, validation/validation.go, validation/validation_test.go
Suite de PR #309.
- ajout de JSON Schemas pour les types `APConso`, `APDemande`, `CCSF`, `Delai` et `Procol`
1. création d'un nouveau JSON Schema (vierge) dans le répertoire `validation/` => erreur de `go test` (fichier non référencé)
2. référencement du JSON Schema dans `validation/validation_test.go` => erreurs de `go test` (propriétés manquantes)
3. complétion du JSON Schema en s'appuyant sur le type Go en sortie du parseur => plus d'erreurs de `go test` ✅
4. dans la codebase TS: chargement du type depuis `GeneratedTypes.ts` au lieu de le définir dans `RawDataTypes.ts` => `go generate` passe sans erreurs ✅
5. si le JSON Schema est valide et que les types sont bien alignés, aucune erreur de validation ne sera listée par `test-import.sh` ✅
- Couvrir les types restants
- Généraliser la …
=> feat(types): Alignement des types entre Go et TypeScript – partie 2

handlers.go, tests/output-snapshots/test-check.golden.txt, tests/test-check.sh
En travaillant sur la PR #335, l'ordre des rapports générés par `sfdata check` a encore changé, comme dans la [PR #334](https://github.com/signaux-faibles/opensignauxfaibles/pull/334/files#diff-fc9abfbc3f2c2438ac1e157c22e8e449925c2f81b6459f4171775581cb59be45). Ces changements impliquent le besoin de mettre à jour le golden file de `test-check.sh` alors qu'en réalité `sfdata` se comporte comme d'habitude.
Figer l'ordre des rapports une fois pour toute, en utilisant un tri par nom de fichier.
=> fix(tests): Figer l'ordre des rapports de `sfdata check`

.github/semantic-pr-title.yml, .github/semantic.yml
Vu qu'on _squash_ les commits lorsqu'on fusionne une PR dans la branche principale du dépôt, le titre de la PR devient le message de commit qui sera intégré dans cette branche.
Sachant que la normalisation des messages de commits permet une meilleure lisibilité de la nature des changements apportés et un comptage automatique des numéros de versions, il serait pratique que GitHub nous prévienne lorsqu'un titre de PR n'est pas normalisé au format Conventional Commit.
Installation de ~~[coleHafner/semantic-pr-title: GitHub app to enforce Angular commit conventions for PR title](https://github.com/coleHafner/semantic-pr-title)~~ [GitHub Apps - Semantic Pull Requests](https://github.com/apps/semantic-pull-requests). (comme dans `prepare-import`)
=> fix(CI): Validation du titre des PRs

lib/marshal/parser.go, parseFileHandler.go
- rendre la logique d'extraction de tuples et d'erreurs plus lisible et maintenable, en cloisonnant les responsabilités de chaque fonction
- dé-dupliquer le code de `marshal.ParseFilesFromBatch()`, appelé dans `parseFileHandler.go` (commande `parseFile` de `sfdata`)
=> fix: Dé-duplication & découpage du pilotage de parseurs

js/reduce.algo2/finalize.ts, js/reduce.algo2/finalize_tests.ts, lib/engine/jsFunctions.go
Bugs découverts en augmentant la couverture de tests des traitements map-reduce, dans PR #348:
1. Les variables `effectif_entreprise`, `apart_entreprise` et `debit_entreprise` rattachées à chaque établissement de `Features` sont des valeurs intermédiaires au lieu de représenter le total calculé sur tous les établissements de l'entreprise. (cf 3 diffs ci-dessous)
2. La variable `effectif_entreprise` vaut systématiquement l'effectif du premier établissement de l'entreprise (cf 1er diff ci-dessous)
```
reduce.algo2 › finalize_tests.ts › finalize() fait la somme des effectifs des établissement rattachés à l'entreprise
Difference:
[
{
effectif: 3,
-     effectif_entreprise: 3,
+     effectif_entreprise: 7,
nbr_etablissements_connus: 2,
siret: '12345678901234',
},
{
effectif: 4,
- …
```
=> fix(Features): Correction du calcul des totaux par entreprise

lib/engine/adminBatch.go, lib/marshal/mapping.go, lib/marshal/mapping_test.go
Vérifier que les fichiers `admin_urssaf` (comptes) gzippés sont supportés par `sfdata import`.
Transmission de l'instance `BatchFile` (avec son préfixe `gzip:`) à jusqu'à la fonction `OpenFileReader()`, au lieu d'en extraire le chemin sans son préfixe, dans `OpenAndReadSiretMapping()`.
=> fix(import): Support des fichiers comptes "admin_urssaf" compressés

lib/marshal/parser_test.go, lib/marshal/tracker.go, lib/marshal/tracker_test.go, lib/urssaf/urssaf_test.go, tests/output-snapshots/test-check.golden.txt, tests/output-snapshots/test-import.golden.txt
Fix #353.
Cf `"linesValid" : -668053` dans l'extrait de document de la collection `Journal`, ci-dessous:
```
{
"_id" : ObjectId("607ea0aaef6c0e5bec291a61"),
"commitHash" : "396671ce2c716b494453bce942aaa76d981cd720",
"event" : {
"linesParsed" : 31058331,
"linesRejected" : 2533049,
"summary" : "/2104/StockEtablissement_utf8_geo.csv: intégration terminée, 31058331 lignes traitées, 0 erreurs fatales, 2533049 lignes rejetées, 29193335 lignes filtrées, -668053 lignes valides",
"linesValid" : -668053,
"linesSkipped" : 29193335,
},
"priority" : "info",
"parserCode" : "sirene",
"reportType" : "ImportBatch"
}
```
Forcer l'usage du type `int64` au lieu de `int32` pour exprimer un nombre de lignes supérieur à 2 millions. (ce qui est le cas du fichier concerné)
=> fix(import): Nombre négatif de lignes valides rapportées dans Journal

.github/workflows/ci.yml, .github/workflows/container.yml, Makefile, README.md, test-all.sh
"go generate" était utilisé pour la génération de code. Les fonctionnalités pour lesquelles c'était requis ont disparu, on peut donc retirer tous les appels à "go generate" et la documentation associée.
=> refactor: retrait des "go generate"
